export const challenges = [
  { title: 'Analog Clock', link: 'analog-clock' },
  { title: 'Loan Calculator', link: 'Mortgage_Loan_Calculator' },
  { title: 'Expanding Cards', link: 'expanding_cards' },
  { title: 'Progress steps', link: 'progress_steps' },
  { title: 'Rotating Navbar Animation', link: 'rotating-nav-animation' },
  { title: 'Light & Dark mode', link: 'light-dark-mode', isComingUp: true },
  { title: 'Toast Popup', link: 'toast-popup', isComingUp: true },
  { title: 'CSS Shapes', link: 'css-shapes', isComingUp: true },
  { title: 'Password Strength', link: 'password-strength', isComingUp: true },
  { title: 'Star Rating', link: 'star-rating', isComingUp: true },
  { title: 'Pixel Art', link: 'pixel-art', isComingUp: true },
  { title: 'Color Spotter', link: 'color-spotter', isComingUp: true },
  { title: 'Todo List', link: 'todo-list', isComingUp: true },
  { title: 'Transfer List', link: 'transfer-list', isComingUp: true },
  { title: 'Tic-Tac-Toe', link: 'tic-tac-toe', isComingUp: true },
  { title: 'Chess board', link: 'chess-board', isComingUp: true },
  { title: 'Skeleton Loader', link: 'skeleton_loader', isComingUp: true },
  { title: 'Chips Input', link: 'chips-input', isComingUp: true },
  { title: 'Password Generator', link: 'password-generator', isComingUp: true },
  { title: 'Basic calculator', link: 'basic-calculator', isComingUp: true },
  { title: 'Navigation Bar', link: 'navigation_bar', isComingUp: true },
  { title: 'Match Pair', link: 'match-pair', isComingUp: true },
  { title: 'Typing Speed Test', link: 'typing-speed-test', isComingUp: true },
  { title: 'Countdown Timer', link: 'count-down-timer', isComingUp: true },
  { title: 'OTP Input', link: 'otp-input', isComingUp: true },
  { title: 'Area Selector', link: 'area-selector', isComingUp: true },
  { title: 'Carousel', link: 'carousel', isComingUp: true },
  { title: 'Calendar', link: 'calendar', isComingUp: true },
  { title: 'Paginator', link: 'paginator', isComingUp: true },
  { title: 'Connect Four', link: 'connect-four', isComingUp: true },
  { title: 'Comment box', link: 'comment-box', isComingUp: true },
  { title: 'JSON Creator', link: 'json-creator', isComingUp: true },
  { title: 'Array methods', link: 'array-methods', isComingUp: true },
  { title: 'Progress Bar', link: 'progress-bar', isComingUp: true },
  { title: 'Stepper', link: 'stepper', isComingUp: true },
  { title: 'Accordion', link: 'accordion', isComingUp: true },
  { title: 'Autocomplete', link: 'autocomplete', isComingUp: true },
  { title: 'Dialog Popup', link: 'dialog_popup', isComingUp: true },
  { title: 'Sort Table', link: 'sort_table', isComingUp: true },
  { title: 'Emoji Editor', link: 'emoji_editor', isComingUp: true },
  { title: 'Infinite Scroll', link: 'infinite_scroll', isComingUp: true },
];
